### ISSUE TITLE
Create Github App

### ISSUE THREAD

**Issue by tumido** [open-services-group/peribolos-as-a-service#5]
1. Create an app within the OSG GitHub org (Creator needs to be a OSG org admin)
2. Investigate authentication flow (do we need a callback URL?)
3. Generate Client Secret

**Comment by tumido** [comment]
Tasks left:
- [ ] Transfer the app to OSG org

**Comment by Shreyanand** [comment]
[Application](https://github.com/apps/peribolos-service) with transferred ownership. 
@tumido lmk if it looks good and if we can close this issue.

**Comment by tumido** [comment]
Looks great! Closing it now. Thanks @Shreyanand ! :+1:
