### ISSUE TITLE
Setup CI for releasing

### ISSUE THREAD

**Issue by tumido** [open-services-group/peribolos-as-a-service#70]
Setup automation for release process. Right now from tag push/GH release creation to deployment is covered. Automate the release/tag creation/version bump as well.

**Comment by tumido** [comment]
For proper release cycle we want to have 2 stages of shared environment called `stage` and `prod` + 1 individual dev stage called `dev`.

1. `dev` environment tracks the `main` branch (or individual changes on top of that) for images and manifests and is not managed by ArgoCD
2. `stage` environment tracks a fixed commit/tag images. When release is performed, the codebase available in `main` branch is bundled as a container image. This image is used by manifests in `stage` overlay. ArgoCD manages this environment in a way that manifests are using `main` branch as reference, so we can benefit from ArgoCD rollback.
3. `prod` environment uses `stage` content after an explicit promotion. This environment uses images already validated by `stage` environment - the same images. ArgoCD manages this environment in a way that manifests are using `main` branch as reference, so we can benefit from ArgoCD rollback. The only difference between `stage` and `prod` manifests after promotion is the namespace and app credentials.

Proposed idea:

Release process is triggered by GitHub issue that only maintainers can trigger. Using issue templates for:
- Release:
   1. Updates version in `package.json` and `stage` manifests references
   2. Generates changelog for a release
   3. Build and push images (so it's available at the time merge happens)
   4. Pushes updated content as a PR (after it is merged, ArgoCD synces manifests)
   5. After PR is merged, creates a tag and github release so it also includes the new content

- Promote to prod:
   1. Update version in `prod` manifests to match `stage` reference
   2. Push changes as a PR (after it is merged, ArgoCD synces manifests)

Additional CI:
- On PR merge we build images as `:latest` so they can be used in `dev`

Outcomes:
- Bypasses AICoE CI because that builds from tag and we need to ensure the images are available when we're updating manifests for `stage`
- We're not rebuilding images for `prod`, we're reusing `stage` content

**Comment by tumido** [comment]
cc @mimotej @harshad16 @KPostOffice @SamoKopecky

**Comment by tumido** [comment]
> what does it mean that codebase is bundled as a container image, is it from a tag or commit?

The point is that we should maintain consistency and parity between repository commits and container images. Tags are treated as commits here.

> i m not quite understanding the flow, what would be updated stage manifests in step 1 if the github tag is to be created as step 5 ?

Let me try to rephrase it, if I git checkout to a release -> I checkout a tag. And the repository at this HEAD should contain all the released content: Changelog, version bumps, manifests referencing the new release and so on.

Stage 1 updates the versions to the release in preparation by the pipeline, while step 5 propagates it to main branch so it's noticed by ArgoCD.

> aicoe-ci update manifests,when it ensure the build was successful.

Yes, but the manifest upgrade is not part of the release tag. Hence checking out to the release tag e.g. `v1.2.3` gives you manifest pointers to `v1.2.2` which is inconsistent.

**Comment by harshad16** [comment]
Thanks for the explanation, ack on the rest of the points.

> Yes, but the manifest upgrade is not part of the release tag. Hence checking out the release tag e.g. `v1.2.3` gives you manifest pointers to `v1.2.2` which is inconsistent.

just FYI aicoe-ci update manifests with the tag it built and pushed to the registry in one flow.
