### ISSUE TITLE
Handle app uninstall

### ISSUE THREAD

**Issue by tumido** [open-services-group/peribolos-as-a-service#8]
Implements: https://github.com/open-services-group/peribolos-as-a-service/blob/fab17cbeb13e9ec6d95ffed4b7952089558583cd/architecture.md#user-unsubscribe
Depends on: https://github.com/open-services-group/peribolos-as-a-service/issues/4

1. Receive "install" webhook with "delete" action
2. Delete installation specific secret

Run a task deleting the `peribolos.yaml` from `.github` repo and opening a PR.

**Comment by schwesig** [comment]
Is it possible to get the secret later and have access for creating a PR to clean up?
